[2025-05-31T21:51:03.839+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T21:50:50.421297+00:00 [queued]>
[2025-05-31T21:51:03.892+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T21:50:50.421297+00:00 [queued]>
[2025-05-31T21:51:03.892+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-31T21:51:03.967+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): log_skipped_reason> on 2025-05-31 21:50:50.421297+00:00
[2025-05-31T21:51:04.016+0000] {standard_task_runner.py:60} INFO - Started process 1471 to run task
[2025-05-31T21:51:04.033+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'evaluate_and_train', 'log_skipped_reason', 'manual__2025-05-31T21:50:50.421297+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/evaluate_and_train.py', '--cfg-path', '/tmp/tmpkvl6zw58']
[2025-05-31T21:51:04.041+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask log_skipped_reason
[2025-05-31T21:51:04.306+0000] {task_command.py:423} INFO - Running <TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T21:50:50.421297+00:00 [running]> on host 9c020e596300
[2025-05-31T21:51:04.796+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='evaluate_and_train' AIRFLOW_CTX_TASK_ID='log_skipped_reason' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T21:50:50.421297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-31T21:50:50.421297+00:00'
[2025-05-31T21:51:06.673+0000] {logging_mixin.py:188} WARNING - 2025/05/31 21:51:06 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-31T21:51:07.011+0000] {logging_mixin.py:188} WARNING - 2025/05/31 21:51:07 INFO mlflow.tracking._tracking_service.client: üèÉ View run batch_skipped at: http://172.17.0.1:30500/#/experiments/1/runs/6f98ae4bb05f43a7ae5a32caca92fd27.
[2025-05-31T21:51:07.011+0000] {logging_mixin.py:188} WARNING - 2025/05/31 21:51:07 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://172.17.0.1:30500/#/experiments/1.
[2025-05-31T21:51:07.084+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-31T21:51:07.139+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=evaluate_and_train, task_id=log_skipped_reason, execution_date=20250531T215050, start_date=20250531T215103, end_date=20250531T215107
[2025-05-31T21:51:07.288+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-31T21:51:07.362+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
