[2025-05-31T22:00:21.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T22:00:07.068053+00:00 [queued]>
[2025-05-31T22:00:22.009+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T22:00:07.068053+00:00 [queued]>
[2025-05-31T22:00:22.010+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-31T22:00:22.047+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): log_skipped_reason> on 2025-05-31 22:00:07.068053+00:00
[2025-05-31T22:00:22.139+0000] {standard_task_runner.py:60} INFO - Started process 246 to run task
[2025-05-31T22:00:22.179+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'evaluate_and_train', 'log_skipped_reason', 'manual__2025-05-31T22:00:07.068053+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/evaluate_and_train.py', '--cfg-path', '/tmp/tmpr2vg38g0']
[2025-05-31T22:00:22.187+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask log_skipped_reason
[2025-05-31T22:00:22.526+0000] {task_command.py:423} INFO - Running <TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T22:00:07.068053+00:00 [running]> on host 9c020e596300
[2025-05-31T22:00:23.123+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='evaluate_and_train' AIRFLOW_CTX_TASK_ID='log_skipped_reason' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T22:00:07.068053+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-31T22:00:07.068053+00:00'
[2025-05-31T22:00:24.822+0000] {logging_mixin.py:188} WARNING - 2025/05/31 22:00:24 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-31T22:00:25.513+0000] {logging_mixin.py:188} WARNING - 2025/05/31 22:00:25 INFO mlflow.tracking._tracking_service.client: üèÉ View run batch_skipped at: http://172.17.0.1:30500/#/experiments/1/runs/c6be9a15625d48d7ba285d23942a3b03.
[2025-05-31T22:00:25.515+0000] {logging_mixin.py:188} WARNING - 2025/05/31 22:00:25 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://172.17.0.1:30500/#/experiments/1.
[2025-05-31T22:00:25.713+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-31T22:00:25.776+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=evaluate_and_train, task_id=log_skipped_reason, execution_date=20250531T220007, start_date=20250531T220021, end_date=20250531T220025
[2025-05-31T22:00:26.033+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-31T22:00:26.113+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
