[2025-05-31T22:19:28.096+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T22:19:14.247070+00:00 [queued]>
[2025-05-31T22:19:28.117+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T22:19:14.247070+00:00 [queued]>
[2025-05-31T22:19:28.118+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-31T22:19:28.206+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): log_skipped_reason> on 2025-05-31 22:19:14.247070+00:00
[2025-05-31T22:19:28.235+0000] {standard_task_runner.py:60} INFO - Started process 923 to run task
[2025-05-31T22:19:28.265+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'evaluate_and_train', 'log_skipped_reason', 'manual__2025-05-31T22:19:14.247070+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/evaluate_and_train.py', '--cfg-path', '/tmp/tmp7m96n1cn']
[2025-05-31T22:19:28.279+0000] {standard_task_runner.py:88} INFO - Job 72: Subtask log_skipped_reason
[2025-05-31T22:19:28.515+0000] {task_command.py:423} INFO - Running <TaskInstance: evaluate_and_train.log_skipped_reason manual__2025-05-31T22:19:14.247070+00:00 [running]> on host 9c020e596300
[2025-05-31T22:19:28.948+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='evaluate_and_train' AIRFLOW_CTX_TASK_ID='log_skipped_reason' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T22:19:14.247070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-31T22:19:14.247070+00:00'
[2025-05-31T22:19:30.061+0000] {logging_mixin.py:188} WARNING - 2025/05/31 22:19:30 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-31T22:19:30.157+0000] {logging_mixin.py:188} WARNING - 2025/05/31 22:19:30 INFO mlflow.tracking._tracking_service.client: üèÉ View run batch_skipped at: http://172.17.0.1:30500/#/experiments/1/runs/071d7ee8b1cf40e8b907a08f3f8f1957.
[2025-05-31T22:19:30.158+0000] {logging_mixin.py:188} WARNING - 2025/05/31 22:19:30 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://172.17.0.1:30500/#/experiments/1.
[2025-05-31T22:19:30.182+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-31T22:19:30.213+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=evaluate_and_train, task_id=log_skipped_reason, execution_date=20250531T221914, start_date=20250531T221928, end_date=20250531T221930
[2025-05-31T22:19:30.312+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-31T22:19:30.380+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
